---
title: "Gov 50 Final Project"
author: Cole Cochrane
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the impact on the standard of living from the level of social safety net spending. As the United States sees bigger calls for increased healthcare, social security and other spending on social safety net programs, it would be intriguing to explore the degree to which standards of living are affected by such investments.

Another idea I had in mind for my research is to explore the effects unionization has on the workplace. This includes quality of work, compensation and benefits, turnover rate, etc. etc. We have seen an increasing number of strikes and union-related activities, and it would be interesting to see the benefits from unionization.

## Finding data and writing a proposal

Does the level of healthcare spending in a country affect public health? In this study, I plan on examining the amount in which countries spend on healthcare as a percentage of their GDP, and to then compare their respective life expectancy. I hypothesize that the greater the percentage of GDP is spent on healthcare, the life expectancy would be higher. I expect that as there is greater spending on healthcare, there are larger investments in healthcare infrastructure and more funding for healthcare operations, which would  mean increased services for patients. Consequently, as patients enjoy a higher quality healthcare through larger investments, health problems would decline and would subsequently be reflected in life expectancy. My sample includes measures of healthcare spending from all countries between the years 2000 and 2020, as well as an additional sample on life expectancy by country in the same time period. The explanatory variable of interest is healthcare spending as a percentage of GDP, by country. If the variable were to be coded = 5.76, this means that 5.76% of GDP is spent on healthcare services. This variable is measured from the World Bank's data set on global healthcare expenditures by country. The outcome variable is life expectancy, which if it were to be coded = 65, then the average individual in the given country would live 65 years. This variable is measured by the World Health Organization's data set on life expectancy by country, 1960-2020. If I observe higher life expectancy as the percentage spent on healthcare increases, then it would support my hypothesis. If I observe lower life expectancy as the percentage spent on healthcare decreases, then it would not support my hypothesis. Furthermore, it would also not support my hypothesis if there were to be no relationship between the two variables. When I run my regression on the countries' healthcare spending and life expectancy, and I receive a positive, significant coefficient, then this would indicate support for my hypothesis.  


